#!/usr/bin/env node
// Regenerate the AUTO zones of docs/ui-spec/*.md from the canonical HTML pages.
// MANUAL zones (Nx mapping, design intent) are never touched.
//
//   npm run spec            regenerate AUTO zones in existing spec files
//   npm run spec:scaffold   create missing spec files (skeleton) then regenerate
//   npm run spec:check      exit 1 if any spec file is stale (for pre-commit/CI)
//
// Coupled to page conventions via scripts/ui-spec-parse.mjs.

import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { parse } from 'node-html-parser';
import { parseRootTokens, parseSections, cleanText } from './ui-spec-parse.mjs';

const REPO = dirname(dirname(fileURLToPath(import.meta.url)));
const SPEC_DIR = join(REPO, 'docs', 'ui-spec');
const TOKENS_FILE = join(SPEC_DIR, '_tokens.md');

// Single source of truth for scope: 7 live canonical pages (excludes -old / -v2).
export const PAGES = [
  'home', 'work', 'inside', 'personal', 'about', 'focus-alignment', 'salesx',
];
const BASELINE_PAGE = 'home'; // its :root tokens are the shared baseline

const START = '<!-- AUTO:START — regenerated by `npm run spec`. Do not edit below. -->';
const END = '<!-- AUTO:END -->';
const SPLICE_RE = /<!-- AUTO:START[\s\S]*?-->[\s\S]*?<!-- AUTO:END -->/;

const args = new Set(process.argv.slice(2));
const CHECK = args.has('--check');
const SCAFFOLD = args.has('--scaffold');

function htmlPath(page) { return join(REPO, `${page}.html`); }
function specPath(page) { return join(SPEC_DIR, `${page}.md`); }

/** Tokens on `page` whose value differs from the baseline (or are new). */
function tokenOverrides(pageTokens, baseline) {
  const base = new Map(baseline.map((t) => [t.name, t.value]));
  return pageTokens.filter((t) => base.get(t.name) !== t.value);
}

function renderTokenBlock(overrides) {
  if (!overrides.length) return '### Tokens\n\n- none (inherits baseline from `_tokens.md`)';
  const rows = overrides.map((t) => `- \`${t.name}\`: ${t.value}`).join('\n');
  return '### Tokens (overrides vs `_tokens.md`)\n\n' + rows;
}

function renderSectionBlock(sections) {
  if (!sections.length) return '### Section inventory\n\n- ⚠️ no top-level `<section>` found';
  const lines = sections.map((s) => {
    const id = s.id ? ` \`#${s.id}\`` : '';
    const cls = s.class ? `**${s.class.split(/\s+/)[0]}**` : '**(section)**';
    const parts = [];
    if (s.heading) parts.push(`H: "${s.heading}"`);
    if (s.cta) parts.push(`CTA: "${s.cta}"`);
    if (s.assets.length) parts.push(`assets: ${s.assets.join(', ')}`);
    const detail = parts.length ? ` — ${parts.join(' · ')}` : '';
    return `${s.index}. ${cls}${id}${detail}`;
  });
  return '### Section inventory\n\n' + lines.join('\n');
}

function buildAutoZone(page, baseline) {
  const html = readFileSync(htmlPath(page), 'utf8');
  const root = parse(html);
  const tokens = parseRootTokens(html);
  const sections = parseSections(root);
  const overrides = page === BASELINE_PAGE ? [] : tokenOverrides(tokens, baseline);
  const body = [renderTokenBlock(overrides), '', renderSectionBlock(sections)].join('\n');
  return { zone: `${START}\n\n${body}\n\n${END}`, tokens, sections };
}

function renderTokensBaseline(baseline) {
  const rows = baseline.map((t) => `| \`${t.name}\` | ${t.value} |`).join('\n');
  return `${START}\n\n### Design tokens (baseline from \`${BASELINE_PAGE}.html\` \`:root\`)\n\n` +
    `| Token | Value |\n|-------|-------|\n${rows}\n\n${END}`;
}

function tokensSkeleton() {
  return `# Design Tokens — shared baseline

Baseline token set for the marketing UI. Per-page spec files list only their
**overrides** vs this table. Auto-generated from \`${BASELINE_PAGE}.html\`.

${START}
${END}
`;
}

function pageSkeleton(page) {
  return `# ${page}.html — UI Spec

${START}
${END}

## Nx mapping (manual)

_Map each section to its counterpart in \`apps/infina-ai\`. Use \`(not ported)\` or \`(verify in nx)\` where no clean counterpart exists._

| Section | Nx component (path) | Route |
|---------|---------------------|-------|
|         |                     |       |

## Design intent & interactions (manual)

-
`;
}

/** Splice the AUTO zone into `existing`, preserving everything else byte-for-byte. */
function splice(existing, zone, page) {
  if (!SPLICE_RE.test(existing)) {
    console.warn(`  ⚠️  ${page}.md: AUTO markers missing — skipped (run --scaffold or add markers)`);
    return null;
  }
  // Use a replacer function, NOT a string: `zone` is HTML-derived copy that may
  // contain `$` (e.g. "$50/mo"), which String.replace would treat as a special
  // pattern ($&, $', $1…) and could splice the MANUAL zone into the AUTO zone.
  return existing.replace(SPLICE_RE, () => zone);
}

function run() {
  if (SCAFFOLD && !existsSync(SPEC_DIR)) mkdirSync(SPEC_DIR, { recursive: true });

  const baseline = parseRootTokens(readFileSync(htmlPath(BASELINE_PAGE), 'utf8'));
  let stale = 0;
  let wrote = 0;
  let errors = 0; // broken states (missing file / missing markers) — must fail --check

  // _tokens.md — shared baseline table (auto-synced like the page files).
  if (!existsSync(TOKENS_FILE)) {
    if (SCAFFOLD) writeFileSync(TOKENS_FILE, tokensSkeleton());
    else { console.warn('  ⚠️  _tokens.md missing — run `npm run spec:scaffold`'); errors++; }
  }
  if (existsSync(TOKENS_FILE)) {
    const existing = readFileSync(TOKENS_FILE, 'utf8');
    const next = splice(existing, renderTokensBaseline(baseline), '_tokens');
    if (next === null) errors++;
    else if (next !== existing) {
      stale++;
      console.log(`  ${'_tokens'.padEnd(16)} baseline=${baseline.length} → ${CHECK ? 'STALE' : 'updated'}`);
      if (!CHECK) { writeFileSync(TOKENS_FILE, next); wrote++; }
    }
  }

  for (const page of PAGES) {
    if (!existsSync(htmlPath(page))) {
      console.warn(`  ⚠️  ${page}.html not found — skipped`);
      errors++;
      continue;
    }
    const path = specPath(page);
    if (!existsSync(path)) {
      if (SCAFFOLD) {
        writeFileSync(path, pageSkeleton(page));
      } else {
        console.warn(`  ⚠️  ${page}.md missing — run \`npm run spec:scaffold\``);
        errors++;
        continue;
      }
    }

    const { zone, sections, tokens } = buildAutoZone(page, baseline);
    const existing = readFileSync(path, 'utf8');
    const next = splice(existing, zone, page);
    if (next === null) { errors++; continue; }

    const changed = next !== existing;
    if (changed) stale++;
    const flag = changed ? (CHECK ? 'STALE' : 'updated') : 'ok';
    if (!sections.length) console.warn(`  ⚠️  ${page}: 0 sections`);
    console.log(
      `  ${page.padEnd(16)} sections=${String(sections.length).padStart(2)} ` +
      `tokens=${tokens.length} → ${flag}`,
    );
    if (!CHECK && changed) { writeFileSync(path, next); wrote++; }
  }

  if (CHECK) {
    if (stale || errors) {
      const parts = [];
      if (stale) parts.push(`${stale} stale`);
      if (errors) parts.push(`${errors} broken (missing file/markers)`);
      console.error(`\n✗ ${parts.join(', ')}. Run \`npm run spec\` (or \`spec:scaffold\`) and commit.`);
      process.exit(1);
    }
    console.log('\n✓ All spec files up to date.');
    return;
  }
  if (errors) console.warn(`\n⚠️  ${errors} broken file(s) — run \`npm run spec:scaffold\`.`);
  console.log(`\n✓ ${wrote} file(s) updated.`);
}

run();
