#!/usr/bin/env bash
#
# sync-landing-to-pfa.sh — one-way sync of the canonical landing bundle from
# this repo (Web-Infina-AI = source of truth) into a PFA checkout.
#
# Copies the 3 canonical path-sets, regenerates the drift manifest in PFA, and
# prints PFA's resulting diff. It NEVER commits or pushes — it leaves the changes
# unstaged so a human raises the PFA-side PR. PFA landing dirs are read-only
# downstream: author in Web, run this, review the PFA diff.
#
# Usage:  scripts/sync-landing-to-pfa.sh /path/to/infina-pfa-80389
#     or:  PFA_PATH=/path/to/infina-pfa-80389 scripts/sync-landing-to-pfa.sh
#
set -euo pipefail

WEB_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PFA_PATH="${1:-${PFA_PATH:-}}"

if [[ -z "$PFA_PATH" ]]; then
  echo "ERROR: PFA checkout path required (arg 1 or \$PFA_PATH)." >&2
  exit 2
fi
PFA_PATH="$(cd "$PFA_PATH" 2>/dev/null && pwd || true)"
if [[ -z "$PFA_PATH" || ! -d "$PFA_PATH/src" ]]; then
  echo "ERROR: '$1' is not a valid PFA checkout (no src/)." >&2
  exit 2
fi

# The 3 canonical path-sets. Scoped strictly — rsync --delete only ever touches
# these, never anything else in PFA.
COMPONENTS="src/components/landing-v2"
PAGES="src/pages/landing"
STYLES_DIR="src/styles"
MANIFEST_REL="src/landing-sync-manifest.json"   # OUTSIDE the path-sets (not synced, not hashed)

# sha256 helper that works on both Linux (sha256sum) and macOS (shasum).
sha256() { if command -v sha256sum >/dev/null 2>&1; then sha256sum; else shasum -a 256; fi; }

# Deterministic hash of a path-set: per-file content hashes keyed by relative
# path, sorted, then hashed again. Identical content => identical hash on any OS.
hash_dir() { ( cd "$1" && find . -type f | LC_ALL=C sort | while IFS= read -r f; do sha256 < "$f" | cut -d' ' -f1 | tr -d '\n'; printf '  %s\n' "$f"; done | sha256 | cut -d' ' -f1 ); }
hash_glob() { ( cd "$1" && find . -maxdepth 1 -type f -name 'landing*.css' | LC_ALL=C sort | while IFS= read -r f; do sha256 < "$f" | cut -d' ' -f1 | tr -d '\n'; printf '  %s\n' "$f"; done | sha256 | cut -d' ' -f1 ); }

echo "==> Web (source): $WEB_ROOT"
echo "==> PFA (target): $PFA_PATH"

echo "--> syncing $COMPONENTS"
rsync -a --delete "$WEB_ROOT/$COMPONENTS/" "$PFA_PATH/$COMPONENTS/"
echo "--> syncing $PAGES"
rsync -a --delete "$WEB_ROOT/$PAGES/" "$PFA_PATH/$PAGES/"
echo "--> syncing $STYLES_DIR/landing*.css"
rsync -a --delete --include='landing*.css' --exclude='*' "$WEB_ROOT/$STYLES_DIR/" "$PFA_PATH/$STYLES_DIR/"

# Regenerate the manifest from the now-synced content + the Web source commit.
SOURCE_COMMIT="$(git -C "$WEB_ROOT" rev-parse HEAD 2>/dev/null || echo unknown)"
H_COMPONENTS="$(hash_dir "$WEB_ROOT/$COMPONENTS")"
H_PAGES="$(hash_dir "$WEB_ROOT/$PAGES")"
H_STYLES="$(hash_glob "$WEB_ROOT/$STYLES_DIR")"

cat > "$PFA_PATH/$MANIFEST_REL" <<JSON
{
  "_comment": "AUTO-GENERATED by Web-Infina-AI scripts/sync-landing-to-pfa.sh. Do not hand-edit. PFA landing dirs are read-only downstream — edit in Web, re-run sync.",
  "generatedFrom": "Web-Infina-AI",
  "sourceCommit": "$SOURCE_COMMIT",
  "pathSets": {
    "$COMPONENTS": "$H_COMPONENTS",
    "$PAGES": "$H_PAGES",
    "$STYLES_DIR/landing*.css": "$H_STYLES"
  }
}
JSON
echo "--> wrote manifest: $MANIFEST_REL (source commit ${SOURCE_COMMIT:0:9})"

echo ""
echo "==> PFA diff (review + raise PFA-side PR; this script does NOT commit/push):"
git -C "$PFA_PATH" status --short -- "$COMPONENTS" "$PAGES" "$STYLES_DIR" "$MANIFEST_REL" || true
echo ""
git -C "$PFA_PATH" diff --stat -- "$COMPONENTS" "$PAGES" "$STYLES_DIR" "$MANIFEST_REL" || true
echo ""
echo "Done. Next: in PFA, review the diff, commit on a branch, open a PR. CI drift-check will verify the manifest."
